#!/bin/bash

FLAGS=-c1
THREADS=16

jcam() {
  for (( i = 1; i <= $THREADS ; i++ ))
  do
    ./benchmark $FLAGS $1 $2 $i $3 bin/$1 $i $3
  done
}

others() {
  for (( i = 1; i <= $THREADS ; i++ ))
  do
    taskset -c 0-$((i - 1)) ./benchmark $FLAGS $1 c $i $2 bin/${1}_base $2
    taskset -c 0-$((i - 1)) ./benchmark $FLAGS $1 java $i $2 java -cp bin/ ${1} $2
    ./benchmark $FLAGS $1 wool $i $2 bin/${1}_wool -p $i $2
  done
}

test_cc() {
  make clean-benchmarks
  DOVETAIL_CALLCONV=$2 DOVETAIL_TAILCALLS=false make bin/fib
  jcam fib callconv-$1-notail 40

  make clean-benchmarks
  DOVETAIL_CALLCONV=$2 DOVETAIL_TAILCALLS=true make bin/fib
  jcam fib callconv-$1-tail 40
}

test_optlevel() {
  make clean-benchmarks
  DOVETAIL_OPTLEVEL=$2 make benchmarks
  jcam fib $1 40
  jcam nqueens $1 13
  jcam quicksort $1 30000000
  jcam locks $1 1
  jcam locks $1 16
  jcam rwlock $1 1
  jcam rwlock $1 16
  jcam barrier $1 1
  jcam barrier $1 16
}

test_cc stdc      0
test_cc fastcc    8
#test_cc haskell  10 - Bad interaction with GC???
test_cc x86-std  64
test_cc x86-fast 65

test_optlevel none        0
test_optlevel functional  1
test_optlevel closed      2
test_optlevel bounds      3
test_optlevel all         4

make clean-benchmarks
make benchmarks

others fib 40
others nqueens 13
others quicksort 30000000
others rwlock 1
others barrier 1
others locks 1
#others blackscholes 10000

# Very slow so do these last...
others locks 16
others barrier 16
others rwlock 16
