#!/bin/bash -x

make clean

FLAGS=-c1
THREADS=16

jcam() {
  for (( i = 1; i <= $THREADS ; i++ ))
  do
    ./benchmark $FLAGS $1 $2 $i $3 bin/$1 $i $3
  done
}

others() {
  for (( i = 1; i <= $THREADS ; i++ ))
  do
    cores=$(seq -s, 0 2 $((2*i-1)))
    taskset -c $cores ./benchmark $FLAGS $1 c $i $2 bin/${1}_base $2
    taskset -c $cores ./benchmark $FLAGS $1 java $i $2 java -cp bin/ ${1} $2
    ./benchmark $FLAGS $1 wool $i $2 bin/${1}_wool -p $i $2
  done
}

test_cc() {
  make clean-benchmarks
  DOVETAIL_CALLCONV=$2 DOVETAIL_TAILCALLS=false make bin/fib
  jcam fib callconv-$1-notail 40

  make clean-benchmarks
  DOVETAIL_CALLCONV=$2 DOVETAIL_TAILCALLS=true make bin/fib
  jcam fib callconv-$1-tail 40
}

test_optlevel() {
  make clean-benchmarks
  # TODO: tailcalls currently turned off due to new fast implementation.
  DOVETAIL_OPTLEVEL=$2 DOVETAIL_TAILCALLS=false make benchmarks
  jcam fib $1 40
}

test_all() {
  jcam fib $1 40
  jcam fib_inline $1 40
  jcam fib_inline2 $1 40
  jcam nqueens $1 13
  jcam quicksort $1 30000000
  jcam locks $1 1
  jcam locks $1 16
  jcam rwlock $1 1
  jcam rwlock $1 16
  jcam barrier $1 1
  jcam barrier $1 16
  jcam queue $1 1000
  jcam blackscholes $1 5000
}

test_cc stdc      0
test_cc fastcc    8
#test_cc haskell  10 - Bad interaction with GC???
test_cc x86-std  64
test_cc x86-fast 65

test_optlevel none        0
test_optlevel functional  1
test_optlevel closed      2
test_optlevel bounds      3
test_optlevel all         4

# DOVETAIL_DISABLEFAST affect C compilation so need complete clean.
make clean
DOVETAIL_TAILCALLS=false DOVETAIL_DISABLEFAST=1 make -e benchmarks
test_all no-fast

make clean
DOVETAIL_TAILCALLS=false make benchmarks
test_all all

make clean-benchmarks
make benchmarks

others fib 40
others nqueens 13
others quicksort 30000000
others rwlock 1
others barrier 1
others locks 1
others queue 1000

for (( i = 1; i <= $THREADS ; i++ ))
do
  cores=$(seq -s, 0 2 $((2*i-1)))
  taskset -c $cores ./benchmark $FLAGS blackscholes c $i 5000 bin/blackscholes_base $i benchmarks/bs_input
  taskset -c $cores ./benchmark $FLAGS blackscholes java $i 5000 java -cp bin/ blackscholes $i benchmarks/bs_input
  ./benchmark $FLAGS blackscholes wool $i 5000 bin/blackscholes_wool -p $i benchmarks/bs_input
done

# Very slow so do these last...
others locks 16
others barrier 16
others rwlock 16
